### ISSUE TITLE
Unable to change date of play

### ISSUE THREAD

**Issue by marekjeszka** [ccomeaux/boardgamegeek4android#48] opened 2015-04-12 11:13 UTC
On Samsung Galaxy S IV Mini (Android 4.4.2) I am unable to modify date of an already logged play.
Replication is quite obvious:
- open Plays -> selecy any logged play -> press edit button -> press date -> nothing happens

This works without problems on Nexus 9 (Android 5.0.1).

**Comment by ccomeaux** [comment] 2015-04-16 23:25
Which version of the application are you seeing this?

**Comment by marekjeszka** [comment] 2015-04-17 06:31
I have this issue in all versions of 5.0 (in current one and also in 'beta' versions).

**Comment by ccomeaux** [comment] 2015-04-17 22:59
Not sure what's going on here, but I changed the way it was wired up.

**Comment by henkverleye** [comment] 2015-04-18 07:46
Updated the app yesterday and have the same issue: not able to select the date of the play, it seems to be fixed to the date of today.
Android 4.2.2, reproduced on smartphone and tablet.

**Comment by ccomeaux** [comment] 2015-04-18 23:57
Should be fixed in version 5.0.1.

**Closed by ccomeaux** 2015-04-18 23:57 UTC
