### ISSUE TITLE
Loading state displays on top of search screen content

### ISSUE THREAD

**Issue by kamal-kamalmohamed** [ccomeaux/boardgamegeek4android#90] opened 2018-06-03 05:35 UTC
While searching for a game the loading state displays on top of the list content.

**Scenario 1**:
Steps:
- Open app
- Tap on search
- Type any combination of characters
- Observe

Expected:
- The loading state doesn't overlap the text

Actual:
- The loading state overlaps the text

**Scenario 2**:
Steps:
- Open app
- Tap on search
- Search for any game
- Wait for list results
- Type one more character
- Observe

Expected:
- The loading state doesn't overlap the list results

Actual:
- The loading state overlaps the list results

Reported on Android 8.0. Attached screenshots.

In terms of how to fix this I would suggest an horizontal loading state at the top of search results instead of having a full screen one. I'll put together a PR if that's alright.

![screenshot_20180603-120437](https://user-images.githubusercontent.com/12709263/40883554-66f8be7a-6743-11e8-8607-abfee3880dde.png)
![screenshot_20180603-153017](https://user-images.githubusercontent.com/12709263/40883555-672daad6-6743-11e8-8277-c7402675ee90.png)

**Comment by kamal-kamalmohamed** [comment] 2018-06-05 08:31
@ccomeaux Happy with the suggested approach of having an horizontal progress bar just below the search bar? Happy to submit a PR for it. 😄

**Comment by ccomeaux** [comment] 2018-06-06 03:00
The progress bar is working as intended, but I'm not sure my intention is better than your suggestion. So fire away!

**Comment by kamal-kamalmohamed** [comment] 2018-06-08 12:05
Raised PR here: https://github.com/ccomeaux/boardgamegeek4android/pull/92

**Comment by ccomeaux** [comment] 2018-08-27 02:32
Will be in next minor release

**Closed by ccomeaux** 2018-08-27 02:32 UTC
