### ISSUE TITLE
Tapping game from collection / search results often crashes

### ISSUE THREAD

**Issue by zefquaavius** [ccomeaux/boardgamegeek4android#137] opened 2020-04-18 13:16 UTC
Tapping on a game from the [possibly filtered] collection or search results often crashes shortly after it starts trying to load the game data, at least on a Samsung Galaxy A20. I usually can work around by getting to the game through the Plays. So for a new game, I have to log a generic play on BGG; then I can open it in this app and manipulate all the details in your much more pleasant way.

Thanks! Keep up the good work!

**Comment by ccomeaux** [comment] 2020-04-18 13:21
What version of the app is this on?

**Comment by zefquaavius** [comment] 2020-04-18 13:57
Great question. That's the new release candidate, but it was also doing
that in the prior version from a few months ago. I just had been too busy
to complain about it. :^/

Thanks!
N

**Comment by zefquaavius** [comment] 2020-04-18 14:46
Is there a way I can send you logged crash info, or is the app collecting
that already?

**Comment by Vinne2** [comment] 2020-04-19 23:23
I don't have this problem, so this should be related to conflict between app and specific OS.
What Android version do you use? Mine is `Android 9`.

**Comment by zefquaavius** [comment] 2020-04-20 10:55
Good question. I forgot to include that: version 9, kernel 4.4.111-16481871

**Comment by ccomeaux** [comment] 2020-04-28 12:17
Can you see if you have "Debug" checked in Advanced Settings? If so, try disabling it and see if the problem is resolved.

**Comment by zefquaavius** [comment] 2020-04-28 14:24
Holy cow!!!! You mean all this time this has not been behaving on this
device, it's because I had debug mode on? Suddenly, it's loading game info
in full when I select a game, which had never been a problem on any prior
device, but had never worked even once on this one. I couldn't figure out
what was going on. It was also a new version of this app for me, so it was
just too many variables to bother you about the possibility of it being the
fabulous app's fault.

I'm quite shocked that debug mode causes many features not to work.

I just (with debug off) told it to resync the collection. This should be
liberating and empowering! Thank you for the help, and for continuing to
develop your amazing app, Chris!
N

**Comment by ccomeaux** [comment] 2020-04-29 17:40
Well, that's my fault. I put debug mode in place to try to figure out why some people had problems similar to yours. My guess is that I figured out the majority of the problems, then caused some more with my hacky debug code. I'll rip it out completely for the next iteration of the app.

**Comment by zefquaavius** [comment] 2020-04-29 18:33
No problem! When I had troubles, I thought I'd turned it off as an
experiment; clearly not!

It is really great seeing all the new, glorious functionality.

Thank you so much!
N

**Closed** 2020-05-19 02:33 UTC
